services:
  - type: web
    name: gcli2api
    env: docker
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AUTH_KEY
        sync: false
      - key: DATABASE_DSN
        sync: false
