services:
  - type: web
    name: gcli2api
    env: docker
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      # 正确的语法：从你已经在 Render UI 中创建的环境组引入所有变量
      - fromGroup: db-credentials
      
      # 下面这些非秘密变量可以继续留在这里
      - key: database__client
        value: mysql # 如果你用的是 PostgreSQL, 这里要改成 pg
      - key: url
        value: https://${RENDER_EXTERNAL_HOSTNAME}

