services:
  - type: web
    name: gcli2api
    env: docker
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: database__client
        value: mysql
      - key: database__connection__host
        fromService:
          type: pserv
          name: db
          property: host
      - key: database__connection__user
        fromService:
          type: pserv
          name: db
          property: user
      - key: database__connection__password
        fromService:
          type: pserv
          name: db
          property: password
      - key: database__connection__database
        fromService:
          type: pserv
          name: db
          property: database
      - key: url
        value: https://${RENDER_EXTERNAL_HOSTNAME}
  - type: pserv
    name: db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.db
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_USER
        generateValue: true
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        generateValue: true
